// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltoczpuockphngkgbdvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0b2N6cHVvY2twaG5na2diZHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjI5NDYsImV4cCI6MjA2NTczODk0Nn0.v-JvpExFvRwsSrwtiqHt5togERwMbKwNAnUXvrcyR5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});